invoice/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('invoice.views',
        url(r'^$', 'index', name='invoiceindexurl'),
        url(r'^(?P<inv_number>\d+)/$', 'detail', name='invoicedetailurl'),
        url(r'^(?P<inv_number>\d+)/payment/new/$', 'new_payment', name='newpaymenturl'),
        url(r'^(?P<inv_number>\d+)/edit/$', 'edit_invoice', name='editinvoiceurl'),
        url(r'^(?P<inv_number>\d+)/print/$', 'print_invoice', name='printinvoiceurl'),
        url(r'^(?P<inv_number>\d+)/payment/$', 'new_payment', name='invoicepaymenturl'),
        url(r'^new/$', 'new_invoice', name='newinvoiceurl'),
        url(r'^payment/$', 'payment_index', name='paymentindexurl'),
)

wibo/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.views.generic.simple import direct_to_template
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns("",
    url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r"^admin/", include(admin.site.urls)),

    url(r"^account/", include("account.urls")),

    # url(r"^search/", include("haystack.urls")),

    # WIBO URLs
    url(r'^cards/', include('cards.urls')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^invoice/', include('invoice.urls')),
    url(r'^employee/',include('employee.urls')),
    url(r'^sapub/request/$', 'wibo.views.sapub_request', name='jobrequeseturl'),
    url(r'^wibo/logout-all-users/$', 'wibo.views.logout_all_users', name='logoutallurl'),
    url(r'^wibo/cardmigrationextra00091/$', 'wibo.views.cards_migration_extras_0009_1', name='cardsmigrationextra0009url'),
    url(r'^wibo/cardmigrationextra00092/$', 'wibo.views.cards_migration_extras_0009_2', name='cardsmigrationextra0009url'),
    url(r'^wibo/cardmigrationextra00093/$', 'wibo.views.cards_migration_extras_0009_3', name='cardsmigrationextra0009url'),
    url(r"^reports/", include('reports.urls')),
    url(r"^printsmart/$",direct_to_template,{"template":"printsmart_request.html"}, name="printsmarturl"),
    url(r'^select2/', include('django_select2.urls')),
    )

urlpatterns += staticfiles_urlpatterns()

contacts/models.py
from django.db import models
from django.forms import ModelForm
from django import forms
from roi.models import ClientROI

# Create your models here.
class Contact(models.Model):
    """
    Stores information about the client.
    Serves and foreign key for:
        Address
        Telephone
    """
    # Default Price Level Choices
    INTERNAL = "INT"
    EXTERNAL = "EXT"
    PRICE_LEVEL_CHOICES = (
            (INTERNAL, 'internal'),
            (EXTERNAL, 'external')
            )
        
    first_name      = models.CharField(max_length=30)
    last_name       = models.CharField(max_length=30)
    company         = models.CharField('Company or organization',
                                max_length=255)
    department      = models.CharField('Department or major',
                                max_length=255)
    #title           = models.CharField('Position title',
    #                            max_length=255)
    default_price_level = models.CharField(max_length=3,
                                choices=PRICE_LEVEL_CHOICES)
    email           = models.EmailField(max_length=254)
    student_id      = models.CharField('XID number',max_length=10, 
                                null=True, blank=True)
    roi             = models.ForeignKey(ClientROI, null=True, blank=True)
    notes           = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return u"%s %s (%s, %s)" % (self.first_name, self.last_name, 
                self.department,self.company)

class Address(models.Model):
    """
    Stores addresses associated with a client.
    Each address must belong to a client.

    The max_length for these was borrowed from 
    django-shop and django-postal to allow for
    easier use of international address support
    """
    contact         = models.ForeignKey(Contact)
    street_address  = models.CharField('address',
                                max_length=255)
    city            = models.CharField(max_length=20)
    state           = models.CharField(max_length=255)
    postal_code     = models.CharField('zip code',
                                max_length=20)
    country         = models.CharField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return u"%s %s %s %s" % (self.street_address, \
                self.city, self.postal_code, self.state)

class Telephone(models.Model):
    """
    Stores telephone numbers associated with a client.
    Each phone number must belong to a client.
    """
    contact        = models.ForeignKey(Contact)
    
    # Phone Type choices
    CAMPUS  = "CAMP"
    WORK    = "WORK"
    CELL    = "CELL"
    HOME    = "HOME"

    PHONE_TYPE_CHOICES = (
            (CAMPUS, 'campus'),
            (WORK, 'work'),
            (CELL, 'cell'),
            (HOME, 'home')
            )

    phone_type      = models.CharField(max_length=4,
                            choices=PHONE_TYPE_CHOICES)
    phone_number    = models.CharField(max_length=24)

    def __unicode__(self):
        return u"%s (%s)" % (self.phone_number, self.phone_type)

class ContactForm(ModelForm):
    """
    Creates a form based on the model indicated.
    Lets django do all the heavy lifting on.
    """
    class Meta:
        model = Contact

class AddressForm(ModelForm):
    """
    Creates a form based on the Address model.
    Not strickly needed with the inlineformset_factory
    over in the view, but needed to exclude the country field.
    """
    state = forms.CharField( widget =
            forms.TextInput(attrs={'class':'span1'}) )
    postal_code = forms.CharField( widget =
            forms.TextInput(attrs={'class':'span2'}) )
    class Meta:
        model = Address
        exclude = ('country',)

invoice/models.py
import datetime

from django import forms
from django.db import models
from django.conf import settings
#from cards.models import JobCard
from django.forms import ModelForm
from contacts.models import Contact
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class Invoice(models.Model):
    """
    Defines an invoice.
    Relates JobCard objects with payment events
    """
    CASH            = 'CASH'
    CHECK           = 'CHECK'
    IDO             = 'IDO'
    WEB_INV         = 'WEB'
    GIFT_CARD       = 'GIFT'
    MARKETPLACE     = 'MARKET'
    PAYMENT_EVENT_TYPE = (
            (CASH, 'Cash'),
            (CHECK, 'Check'),
            (IDO, 'Interdepartmental Order'),
            (WEB_INV, 'Web Invoice'),
            (GIFT_CARD, 'Gift Certificate'),
            (MARKETPLACE, 'Marketplace'),
            )
    invoice_number  = models.AutoField(primary_key=True)
    payment_type    = models.CharField(max_length=10, \
                            choices=PAYMENT_EVENT_TYPE)
    invoice_date    = models.DateField(auto_now_add=True)
    billing_contact = models.ForeignKey(Contact, related_name='invoice')
    job_cards       = models.ManyToManyField('cards.JobCard', through='InvQuantity')
    invoice_notes   = models.TextField(blank=True, null=True)
    billed          = models.BooleanField(default=False)
    taxable         = models.BooleanField(default=True)
    paid            = models.BooleanField(default=False)
    created_user    = models.ForeignKey(User, related_name="%(app_label)s_%(class)s_created_set")
    created_date    = models.DateTimeField(auto_now_add=True)
    updated_user    = models.ForeignKey(User, related_name="%(app_label)s_%(class)s_updated_set")
    updated_date    = models.DateTimeField(auto_now=True)
    notes           = models.TextField(blank=True, null=True)
    

    def get_invoice_number(self):
        """
        Gets the formated invoice number
        """
        return "%s%05d" % (self.invoice_date.year, self.invoice_number)
    invoice_number_display = property(get_invoice_number)
    # total price
    def _get_price(self):
        """
        grabs the price from all the associated 
        job cards (through InvQuantity objects)
        """
        price = 0
        q = InvQuantity.objects.filter(invoice=self)

        for each in q:
            price += each.units * each.price

        return price

    price = property(_get_price)
    # tax
    def _get_tax(self):
        if self.taxable:
            tax = self.price * settings.TAX_RATE
        else:
            tax = 0

        return tax

    tax = property(_get_tax)
    # total paid
    def _get_total_paid(self):
        """
        add all the payment event amounts together
        """
        paid = 0

        payment_events = PaymentEvent.objects.filter(invoice=self)

        
        if payment_events:
            for each in payment_events:
                paid += each.payment_amount

        return paid

    paid_amount = property(_get_total_paid)

    def _get_grand_total(self):
        """
        calculates the grand total for the invoice
        """
        return self.price + self.tax

    grand_total = property(_get_grand_total)
    # remaining balance
    def _get_balance(self):
        """
        calcuates the balance on the invoice
        price + tax - payments
        """
        return self.grand_total - self.paid_amount

    balance = property(_get_balance)

    def __unicode__(self):
        return "Invoice: %s" % self.invoice_number_display
    
    def get_absolute_url(self):
        return reverse('invoice.views.detail',args=[self.invoice_number])

    def job_list(self):
        string = ''
        for each in self.job_cards.all():
            string = string +  "<a href='/admin/cards/jobcard/%s'>%s</a><br/>" % (each.job_number, each)
        return string
    job_list.allow_tags = True

class PaymentEvent(models.Model):
    """
    Base class for payment events

    **Should not be instantiated by itself...ever**
    """
    CASH            = 'CASH'
    CHECK           = 'CHECK'
    IDO             = 'IDO'
    WEB_INV         = 'WEB'
    GIFT_CARD       = 'GIFT'
    MARKETPLACE     = 'MARKET'
    PAYMENT_EVENT_TYPE = (
            (CASH, 'Cash'),
            (CHECK, 'Check'),
            (IDO, 'Interdepartmental Order'),
            (WEB_INV, 'Web Invoice'),
            (GIFT_CARD, 'Gift Certificate'),
            (MARKETPLACE, 'Marketplace'),
            )

    invoice         = models.ForeignKey(Invoice)
    payment_user    = models.ForeignKey(User, related_name='+')
    payment_date    = models.DateTimeField(auto_now_add=True)
    payment_amount  = models.DecimalField(max_digits=9, decimal_places=3)
    # processed payments have been:
    #   put in the safe (Cash/Check),
    #   sent to SABO (IDO),
    #   forwarded on to WebInvoice,
    #   ect.
    payment_processed = models.BooleanField(default=False)
    # received payments have shown up on our
    # activity report / account statments
    payment_received= models.BooleanField(default=False)
    payment_notes   = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return "Payment: %s, $%s" % (self.pk, self.payment_amount)

    def invoice_detail(self):
        return "<a href='/admin/invoice/invoice/%s'>%s</a><br/>" % (self.invoice.invoice_number, self.invoice)
    invoice_detail.allow_tags = True

    def job_detail(self):
        return self.invoice.job_list()
    job_detail.allow_tags = True

    def billing_contact(self):
        return self.invoice.billing_contact

class PaymentEvent_In_House(PaymentEvent):
    """
    Abstract base class that defines an in-house payment
    contains elements included for all in-house payments
    (i.e. a cash or check payment delievered directly to CB+D)
    """
    receipt_number  = models.CharField(max_length=20)

    class Meta:
        """make the class abstract"""
        abstract=True

class PaymentEventCash(PaymentEvent_In_House):
    """
    Defines a cash payment
    """
    payment_type = models.CharField(max_length=5, default=PaymentEvent.CASH, \
            editable=False)

    def __unicode__(self):
        return "%s - Cash" % super(PaymentEventCash,self).__unicode__()

class PaymentEventCheck(PaymentEvent_In_House):
    """
    Defines a check payment
    """
    payment_type = models.CharField(max_length=5, default=PaymentEvent.CHECK, \
            editable=False)
    check_number    = models.CharField(max_length=50)

    def __unicode__(self):
        return "%s - Check %s" % (super(PaymentEventCheck,self).__unicode__(), \
                self.check_number)

class PaymentEventGiftCard(PaymentEvent_In_House):
    """
    Defines a gift card
    """
    payment_type = models.CharField(max_length=5, default=PaymentEvent.GIFT_CARD, \
            editable=False)
    gift_card_number    = models.CharField(max_length=50)

    def __unicode__(self):
        return "%s - Gift Card %s" % (super(PaymentEventGiftCard,self).__unicode__(), \
                self.gift_card_number)


class PaymentEventIDO(PaymentEvent):
    """
    defines an IDO payment
    """
    payment_type = models.CharField(max_length=5, default=PaymentEvent.IDO, \
            editable=False)
    dept_chartstring= models.CharField(max_length=50)
    approved_by     = models.CharField(max_length=30)
    approved_date   = models.DateField()

    def __unicode__(self):
        return "%s - IDO %s" % (super(PaymentEventIDO,self).__unicode__(), \
                self.dept_chartstring)

class PaymentEventWebInvoice(PaymentEvent):
    """
    defines a record of sending an invoice on 
    to the web invoice system for the University
    """
    payment_type = models.CharField(max_length=5, default=PaymentEvent.WEB_INV, \
            editable=False)
    web_invoice_number  = models.CharField(max_length=20,blank=True,null=True)
    sent_to_client  = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s - Web %s" % (super(PaymentEventWebInvoice,self).__unicode__(), \
                self.web_invoice_number)

class PaymentEventMarketplace(PaymentEvent):
    '''
    defines a payment recieved through Clemson University's web Marketplace
    '''
    payment_type = models.CharField(max_length=10, default=PaymentEvent.MARKETPLACE,\
            editable=False)
    order_number = models.CharField(max_length=20)

    def __unicode__(self):
        return "%s - Marketplace %s" % \
                (super(PaymentEventMarketplace,self).__unicode__(),
                 self.order_number)



# =THROUGH models

class InvQuantity(models.Model):
    """
    defines an intermediary model to relate job cards
    to invoices
    """
    invoice         = models.ForeignKey(Invoice)
    job_card        = models.ForeignKey('cards.JobCard')
    units           = models.DecimalField(max_digits=9, \
            decimal_places=3, default=1)
    def _get_price(self):
        """
        grabs the price from the job cards
        """
        return self.job_card.price

    price = property(_get_price)

    def _get_extended_price(self):
        """
        grabs the extended price (price * units)
        """
        return self.price * self.units

    extended_price = property(_get_extended_price)

    def _get_percentage_invoiced(self):
        """
        adds all the quantity objects associated with
        a job together
        """
        q_objs = InvQuantity.objects.filter(job_card=self.job_card)
        
        percent = 0

        for each in q_objs:
            percent += each.units

        return percent

    percentage_invoiced = property(_get_percentage_invoiced)

    def __unicode__(self):
        return "InvQuantity: invoice %s, job %s, units %s" % \
                (self.invoice, self.job_card, self.units)
# =FORMS

class InvoiceForm(ModelForm):
    """
    Creates a forms based on the invoice model
    """
    class Meta:
        model = Invoice

invoice/forms.py
from django import forms
from django_select2 import *
from django.db.models import Q

from cards.models import JobCard
from contacts.models import Contact

from django.core.exceptions import ValidationError

def validate_fail_always(value):
    raise ValidationError(u'%s not valid. Infact nothing is valid!' % value)

########### Forms ##############

class GetJobSearchForm(forms.Form):
    jobs = ModelSelect2MultipleField(queryset=JobCard.objects, required=False, label='By Job')

class GetClientSearchForm(forms.Form):
    clients = ModelSelect2MultipleField(queryset=Contact.objects, required=False, label='By Contact')

class GetInvSearchForm(forms.Form):
    inv = ModelSelect2MultipleField(queryset=Contact.objects, required=False, label='By Inv No')

wibo/templates/invoice/BKP15DEC/detail.html
{% extends "invoice/index.html" %}

{# inv = Invoice object #}
{# jobs = InvQuantity objects #}

{%block head_title %}{{block.super}} {{ inv.invoice_number }}{% endblock head_title%}

{% block body %}
<h2>Invoice</h2>
<div class="row-fluid"><a class="btn btn-primary" href="{% url invoice.views.edit_invoice inv.pk %}">Edit</a> <a class="btn btn-success" href="{% url invoice.views.print_invoice inv.pk %}">Print</a> <a class="btn btn-info" href="{% url invoice.views.new_payment inv.pk %}">Add Payment</a></div>

{% include "invoice/invoice.html" with inv=inv jobs=jobs %}
<hr/>
<div class="row-fluid">
    <div class="span6">
        <h5>Notes:</h5>
        <p>{{inv.notes|linebreaks}}</p>
    </div>
    <div class="span6"><h5>Invoice Log:</h5> 
        <b>Created by:</b> <a href="{%url employeedetailurl inv.created_user.pk%}">{{inv.created_user.get_full_name|default:"CB+D"}}</a> on {{inv.created_date}}<br/>
        <b>Updated by:</b> <a href="{%url employeedetailurl inv.updated_user.pk%}">{{inv.updated_user.get_full_name|default:"CB+D"}}</a> on {{inv.updated_date}}
    </div>
</div>
{% endblock body %}

wibo/templates/invoice/BKP15DEC/index.html
{% extends "site_base.html" %}
{% load django_select2_tags %}
{% load staticfiles %}
{% load cards_extras %}

{# inv = Invoice object #}

{% block head_title %}Invoices{% endblock head_title %}

{% block extra_style %}
<link href="{% static "css/custom.css" %}" rel="stylesheet" type="text/css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
{% import_django_select2_js %}
{% import_django_select2_css %}
{% endblock extra_style %}

{% block extra_script %}
<script src="{% static "js/backtotop.js" %}"></script>
{% endblock extra_script %}
<a id="#Top"></a>

{% block body %}
<h2>Invoices</h2>
<h3>{{view}} Invoices</h3>
{%if view == 'Unpaid'%}<b>Total Unpaid:</b> {{unpaid_total|currency}} <b>Subtotal Unpaid:</b> {{unpaid_subtotal|currency}}<br />{%endif%}
{% if invoice_list %}<br/>
<form method="get" action="">{#{% csrf_token %}#}
    <div class="form-actions-override">
        <h3>Search</h3>
        {{form_job}} <br/><br/>
        {{form_client}} <br/><br/>
        <input class="btn btn-primary" type="submit" name="list" value="Search" />
    </div>
</form>
{% include "_pagination.html" with page=invoice_list ap="&view="|add:view%}
<table class="table table-striped table-condensed table-hover">
    <thead>
        <tr>
            <th>Invoice Number</th>
            <th>Job Name</th>
            <th>Billing Contact</th>
            <th>Payment Type</th>
            <th>Invoice Date</th>
            <th>Balance</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        {% for inv in invoice_list %}
        {% if inv.balance <= 0.009 %}

        <tr class="warning">
        {% elif inv.balance > 0 %}
        <tr class="error">
        {% else %}
        <tr>
        {%endif%}
            <td><a href={% url invoice.views.detail inv.invoice_number %}>{{ inv.invoice_number }}</a></td>
            <td><ul class="unstyled">{% for job in inv.job_cards.all %}
                    <li><a href="{% url invoice.views.detail inv.invoice_number %}">{{ job.name }}</a></li>
            {% endfor %}</ul></td>
            <td><a href={% url invoice.views.detail inv.invoice_number %}>{{ inv.billing_contact }}</a></td>
            <td><a href={% url invoice.views.detail inv.invoice_number %}>{{ inv.payment_type }}</a></td>
            <td><a href={% url invoice.views.detail inv.invoice_number %}>{{ inv.invoice_date }}</a></td>
            <td>{{inv.balance|currency}}</td>
            <td>{{inv.grand_total|currency}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include "_pagination.html" with page=invoice_list ap="&view="|add:view%}
{% endif %}
{% endblock body %}

wibo/templates/invoice/BKP15DEC/invoice.html
{% load cards_extras %}

{# inv = Invoice object #}
{# jobs = InvQuantity objects #}

<div class="row-fluid">
<div class="span6">
    <b>Date:</b> {{ inv.invoice_date }}<br \>
    <b>Bill to:</b> {{ inv.billing_contact }}<br \>
    <b>Email:</b> {{ inv.billing_contact.email }}<br \>
    {% for address in inv.billing_contact.address_set.all %}
    <b>Address:</b> <br />
    <address>{{ address.street_address }}<br />
    {{ address.city }}, {{ address.state }} {{ address.postal_code }}</address>
    {% endfor %}
    {% for phone in inv.billing_contact.telephone_set.all %}
    <b>Phone:</b> {{ phone.phone_number }}<br \>
    {% endfor %}
    <br />
</div>

<div class="span6">
{# IN HOUSE PAYMENT (CASH/CHECK) #}
{% if inv.payment_type == "WEB" %}
    <b>Billing Department:</b> 4063-Student Affairs Publications<br \>
    <b>Billing Dept. Phone:</b> 864-656-6980<br \>
    <p>This job will be forwarded on to Clemson University Accounts Receivable for processing. You will receive a copy of your invoice in 5 - 7 business days.</p>

{% elif inv.payment_type == "CASH" or inv.payment_type == "CHECK" or inv.payment_type == "GIFT" %}
    <b>Invoice Number:</b> {{inv.invoice_number_display}}<br \>
    <b>Terms:</b> <strong>Payable Upon Delivery</strong><br \>
    <b>Make checks payable to Clemson University</b><br \>

{% elif inv.payment_type == "IDO" %}
    <b>Invoice Number:</b> {{inv.invoice_number_display}}<br \>
    <b>Dept. Providing Service:</b> Student Affairs Publications<br \>
    <b>Dept. No. of Servicing Dept.:</b> 4036<br \>
    <b>Billed To:</b> {{inv.billing_contact}}<br \>
    <b>Department:</b> {{inv.billing_contact.company}}<br \>
    <p><strong>An IDO will be processed from the information below.<br />No futher action is required on your part.</strong></p>

{% elif inv.payment_type == "MARKET" %}
    <b>Invoice Number:</b> {{inv.invoice_number_display}}<br />
    
{% else %}
<p>Payment type not defined in invoice.html</p>

{% endif %}
</div>
</div>
<div class="row-fluid">
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Product or Service</th>
            <th>Qty</th>
            <th>Unit Price</th>
            <th>Extended Amount</th>
        </tr>
    </thead>
    <tbody>
    {% for j in jobs %}
        <tr>
            <td><dl><dt><a style="text-decoration:none;color:#000;" a href="{% url jobdetailurl j.job_card.pk %}">{{ j.job_card.name }} (#{{j.job_card.pk}})</a><br />
                    {{j.job_card.client_notes|default_if_none:""}}</dt>
                    {% for q in j.job_card.cardquantity_set.all %}
                    {% if not q.material %}
                    {% if j.job_card.price_level == "INT" %}<dd>{{q.units}} {{q.product.name}} ({{q.product.price_int|currency}}) {{q.item.client_notes|default_if_none:""}}</dd>
                    {% elif j.job_card.price_level == "EXT" %}<dd>{{q.units}} {{q.product.name}} ({{q.product.price_ext|currency}}) {{q.item.client_notes|default_if_none:""}}</dd>
                    {% else %}Price Level Undefined for invoice.html{% endif %}
                    {% endif %}
                    {% endfor %}</dl></td>
            <td>{{ j.units }}</td>
            <td>{{ j.price|currency}}</td>
            <td>{{ j.extended_price|currency }}</td>
        </td>
    {% endfor %}
    </tbody>
</table>
</div>
<div class="row-fluid">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Date</th>
                <th>Payment Type</th>
                <th>Payment Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for p in inv.paymentevent_set.all %}
            <tr>
                <td>{{p.payment_date|date}}</td>
                <td>
                    {% if p.paymenteventcash %}
                    Cash Payment (Receipt Number: {{p.paymenteventcash.receipt_number}})
                    {% elif p.paymenteventcheck %}
                    Check Payment (Check Number: {{p.paymenteventcheck.check_number}}, Receipt Number: {{p.paymenteventcheck.receipt_number}})
                    {% elif p.paymenteventido %}
                    IDO (Approved By: {{p.paymenteventido.approved_by}} Chartfield String: {{p.paymenteventido.dept_chartstring}})
                    {% elif p.paymenteventwebinvoice %}
                    Web Invoice (Invoice Number: {{p.paymenteventwebinvoice.web_invoice_number}})
                    {% elif p.paymenteventmarketplace %}
                    Marketplace Order: {{p.paymenteventmarketplace.order_number}}
                    {% endif %}
                    [Ref. # {{p.pk}}]<br/>
                    &nbsp;&nbsp;&nbsp;<small>{{p.payment_notes}} <i>({{p.payment_user}}){% if p.payment_processed %} p{%endif%}{% if p.payment_received%} r{%endif%}</i></small>
                </td>
                <td>{{p.payment_amount|currency}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="row-fluid inv-footer">
    <div class="span6">
        <h3>Notes:</h3>
        <p>{{ inv.invoice_notes|linebreaks|default_if_none:"" }}</p>
    </div>
    <div class="span6">
        <table class="table table-striped table-bordered">
            <tr><td><b>Subtotal:</b></td><td>{{inv.price|currency}}</td></tr>
            <tr><td><b>Tax:</b></td><td>{{inv.tax|currency}}</td></tr>
            <tr><td><b>Total:</b></td><td>{{inv.grand_total|currency}}</td></tr>
            <tr><td><b>Payments:</b></td><td>({{inv.paid_amount|currency}})</tr>
            <tr><td><b>Net Due:</b></td><td>{{inv.balance|currency}}</td></tr>
        </table>
        <p>Please make checks out to Clemson University.</p>
    </div>
</div>

wibo/templates/invoice/BKP15DEC/invoice_form.html
{% extends 'invoice/detail.html' %}
{% load bootstrap_tags %}
{% block body %}
<h3>Edit Invoice</h3>
<form action="" method="post">{% csrf_token %}
<div class="row">
 <div class="span4">
     {{ form|as_bootstrap }}
 </div>{#span4#}
 <div class="span8">
     <h4>Instructions:</h4>
     <strong><em>Payment Type:</em></strong> How the client has paid/will pay.<br/>
     <strong><em>Billing Client:</em></strong> Who's paying for the invoice.<br/>
     <b>Invoice notes:</b> Notes for the client (this will show up on the invoice).<br/>
     <b>Notes:</b> Notes for internal use only (this does not show up on the invoice).<br/>
 </div>{#span8#}
</div>{#row#}
     {% include "formset_table.html" with formset=job_formset %}
     <div class="form-actions">
         <input class="btn btn-primary" type="submit" value="Save" />
         <input class="btn" type="button" value="Cancel" onClick="history.go(-1);return true;" />
     </div>
 </form>
 {% endblock body %}