contacts/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('contacts.views',
        url(r'^$',                     'index', name='contactsindexurl'),
        url(r'^(?P<contact_id>\d+)/$', 'detail', name='contactdetailsurl'),
        url(r'^new/$',                 'new_contact', name='newcontacturl'),
        url(r'^(?P<contact_id>\d+)/edit/$','edit_contact', name='editcontacturl'),

)

wibo/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.views.generic.simple import direct_to_template
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns("",
    url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r"^admin/", include(admin.site.urls)),

    url(r"^account/", include("account.urls")),

    # url(r"^search/", include("haystack.urls")),

    # WIBO URLs
    url(r'^cards/', include('cards.urls')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^invoice/', include('invoice.urls')),
    url(r'^employee/',include('employee.urls')),
    url(r'^sapub/request/$', 'wibo.views.sapub_request', name='jobrequeseturl'),
    url(r'^wibo/logout-all-users/$', 'wibo.views.logout_all_users', name='logoutallurl'),
    url(r'^wibo/cardmigrationextra00091/$', 'wibo.views.cards_migration_extras_0009_1', name='cardsmigrationextra0009url'),
    url(r'^wibo/cardmigrationextra00092/$', 'wibo.views.cards_migration_extras_0009_2', name='cardsmigrationextra0009url'),
    url(r'^wibo/cardmigrationextra00093/$', 'wibo.views.cards_migration_extras_0009_3', name='cardsmigrationextra0009url'),
    url(r"^reports/", include('reports.urls')),
    url(r"^printsmart/$",direct_to_template,{"template":"printsmart_request.html"}, name="printsmarturl"),
    url(r'^select2/', include('django_select2.urls')),
    )

urlpatterns += staticfiles_urlpatterns()

contacts/models.py
from django.db import models
from django.forms import ModelForm
from django import forms
from roi.models import ClientROI

# Create your models here.
class Contact(models.Model):
    """
    Stores information about the client.
    Serves and foreign key for:
        Address
        Telephone
    """
    # Default Price Level Choices
    INTERNAL = "INT"
    EXTERNAL = "EXT"
    PRICE_LEVEL_CHOICES = (
            (INTERNAL, 'internal'),
            (EXTERNAL, 'external')
            )
        
    first_name      = models.CharField(max_length=30)
    last_name       = models.CharField(max_length=30)
    company         = models.CharField('Company or organization',
                                max_length=255)
    department      = models.CharField('Department or major',
                                max_length=255)
    #title           = models.CharField('Position title',
    #                            max_length=255)
    default_price_level = models.CharField(max_length=3,
                                choices=PRICE_LEVEL_CHOICES)
    email           = models.EmailField(max_length=254)
    student_id      = models.CharField('XID number',max_length=10, 
                                null=True, blank=True)
    roi             = models.ForeignKey(ClientROI, null=True, blank=True)
    notes           = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return u"%s %s (%s, %s)" % (self.first_name, self.last_name, 
                self.department,self.company)

class Address(models.Model):
    """
    Stores addresses associated with a client.
    Each address must belong to a client.

    The max_length for these was borrowed from 
    django-shop and django-postal to allow for
    easier use of international address support
    """
    contact         = models.ForeignKey(Contact)
    street_address  = models.CharField('address',
                                max_length=255)
    city            = models.CharField(max_length=20)
    state           = models.CharField(max_length=255)
    postal_code     = models.CharField('zip code',
                                max_length=20)
    country         = models.CharField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return u"%s %s %s %s" % (self.street_address, \
                self.city, self.postal_code, self.state)

class Telephone(models.Model):
    """
    Stores telephone numbers associated with a client.
    Each phone number must belong to a client.
    """
    contact        = models.ForeignKey(Contact)
    
    # Phone Type choices
    CAMPUS  = "CAMP"
    WORK    = "WORK"
    CELL    = "CELL"
    HOME    = "HOME"

    PHONE_TYPE_CHOICES = (
            (CAMPUS, 'campus'),
            (WORK, 'work'),
            (CELL, 'cell'),
            (HOME, 'home')
            )

    phone_type      = models.CharField(max_length=4,
                            choices=PHONE_TYPE_CHOICES)
    phone_number    = models.CharField(max_length=24)

    def __unicode__(self):
        return u"%s (%s)" % (self.phone_number, self.phone_type)

class ContactForm(ModelForm):
    """
    Creates a form based on the model indicated.
    Lets django do all the heavy lifting on.
    """
    class Meta:
        model = Contact

class AddressForm(ModelForm):
    """
    Creates a form based on the Address model.
    Not strickly needed with the inlineformset_factory
    over in the view, but needed to exclude the country field.
    """
    state = forms.CharField( widget =
            forms.TextInput(attrs={'class':'span1'}) )
    postal_code = forms.CharField( widget =
            forms.TextInput(attrs={'class':'span2'}) )
    class Meta:
        model = Address
        exclude = ('country',)

contacts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404, render
from django.template import Context, loader
from django.forms.models import inlineformset_factory
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from contacts.models import Contact, Address, Telephone, ContactForm, AddressForm
from cards.models import JobCard

@login_required(login_url='/account/login/')
def index(request):
    contact_list = Contact.objects.all().order_by('last_name')
    return render_to_response('contacts/index.html', {'contact_list': contact_list},
            RequestContext(request))

@login_required(login_url='/account/login/')
def detail(request, contact_id):
    c = get_object_or_404(Contact, pk=contact_id)
    opened_list = JobCard.objects.filter(contact=c).filter(billed=False)
    completed_list = JobCard.objects.filter(contact=c).filter(billed=True)

    if not request.POST:
        return render_to_response('contacts/detail.html',{
            'contact':c,
            'opened_list':opened_list,
            'completed_list':completed_list,
            },RequestContext(request))

@login_required(login_url='/account/login/')
def new_contact(request):
    print "new_contact"

    AddressInlineFormSet = inlineformset_factory(Contact, Address, form=AddressForm, extra=1)
    TelephoneInlineFormSet = inlineformset_factory(Contact, Telephone, extra=1)

    if request.method == "POST":
        form = ContactForm(request.POST)
        address_formset = AddressInlineFormSet(request.POST, request.FILES)
        telephone_formset = TelephoneInlineFormSet(request.POST, request.FILES)

        if form.is_valid() and address_formset.is_valid() and telephone_formset.is_valid():
            contact = form.save()
            addresses = address_formset.save(commit=False)
            for a in addresses:
                a.contact_id = contact.pk
                a.save()
            phones = telephone_formset.save(commit=False)
            for p in phones:
                p.contact_id = contact.pk
                p.save()
            address_formset.save_m2m()
            telephone_formset.save_m2m()

            return HttpResponseRedirect(reverse('contacts.views.detail', args=(contact.pk,)))
    else:
        form = ContactForm()
        address_formset = AddressInlineFormSet()
        telephone_formset = TelephoneInlineFormSet()

    return render_to_response("contacts/form.html",{
        "form":form,
        "address_formset":address_formset,
        "telephone_formset":telephone_formset,
        },RequestContext(request))

@login_required(login_url='/account/login/')
def edit_contact(request, contact_id):
    contact = Contact.objects.get(pk=contact_id)

    AddressInlineFormSet = inlineformset_factory(Contact, Address, form=AddressForm, extra=1)
    TelephoneInlineFormSet = inlineformset_factory(Contact, Telephone, extra=1)

    if request.method == "POST":
        form = ContactForm(request.POST, instance=contact)
        address_formset = AddressInlineFormSet(request.POST, request.FILES, instance=contact)
        telephone_formset = TelephoneInlineFormSet(request.POST, request.FILES, instance=contact)
        if form.is_valid() and address_formset.is_valid() and telephone_formset.is_valid():
            form.save()
            address_formset.save()
            telephone_formset.save()
            return HttpResponseRedirect(reverse('contacts.views.detail', args=(contact.pk,)))
    else:
        form = ContactForm(instance=contact)
        address_formset = AddressInlineFormSet(instance=contact)
        telephone_formset = TelephoneInlineFormSet(instance=contact)
    return render_to_response("contacts/form.html", {
        "form": form,
        "address_formset": address_formset,
        "telephone_formset": telephone_formset,
        },RequestContext(request))

wibo/views.py
import datetime
 
from django.conf import settings
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.http import HttpRequest
from django.utils.importlib import import_module

from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, user_passes_test

from cards.models import *
 
 
def init_session(session_key):
    """
    Initialize same session as done for ``SessionMiddleware``.
    """
    engine = import_module(settings.SESSION_ENGINE)
    return engine.SessionStore(session_key)
 

@login_required(login_url='/account/login/')
@user_passes_test(lambda u: u.groups.filter(name='admin').count(), login_url='/')
def logout_all_users(request):
    """
    Read all available users and all available not expired sessions. Then
    logout from each session.
    """
    now = datetime.datetime.now()
    request = HttpRequest()
 
    sessions = Session.objects.filter(expire_date__gt=now)
    users = dict(User.objects.values_list('id', 'username'))
 
    print('Found %d not-expired session(s).' % len(sessions))
 
    for session in sessions:
        username = session.get_decoded().get('_auth_user_id')
        request.session = init_session(session.session_key)
 
        logout(request)
        print('    Successfully logout %r user.' % username)
 
    print('All OK!')
    return HttpResponseRedirect('/')

@login_required(login_url="/account/login/")
def sapub_request(request):
    form = JobForm()

    if request.method == "POST":
        form = JobForm(request.POST)

        if form.is_valid():
            job = form.save()
            return HttpResponseRedirect(reverse('cards.views.job_detail',args=(job.pk,) ))

    else:
        form = JobForm()

    return render_to_response("sapub_request.html",{
        "form":form,
        },RequestContext(request))


@login_required(login_url='/account/login/')
@user_passes_test(lambda u: u.groups.filter(name='admin').count(), login_url='/')
def cards_migration_extras_0009_1(request):
    quantcards = CardQuantity.objects.all()
    for q in quantcards:
        if q.material != None and q.product != None and q.job_card == None:
            q.qtype = CardQuantity.MATERIAL
        elif q.product != None and q.job_card != None and q.material == None:
            q.qtype = CardQuantity.PRODUCT

        print q
        q.save()
    return HttpResponseRedirect('/')

@login_required(login_url='/account/login/')
@user_passes_test(lambda u: u.groups.filter(name='admin').count(), login_url='/')
def cards_migration_extras_0009_2(request):
    prodcards = ProductCard.objects.all()
    for p in prodcards:
        p.name = p.product_name
        p.assigneduser = User.objects.get(pk=p.designer.pk)
        print p
        p.save()
    return HttpResponseRedirect('/')

@login_required(login_url='/account/login/')
@user_passes_test(lambda u: u.groups.filter(name='admin').count(), login_url='/')
def cards_migration_extras_0009_3(request):
    jobcards = JobCard.objects.all()
    for j in jobcards:
        j.name = j.job_name
        j.prod_notes = j.job_notes

        print j
        j.save()
    return HttpResponseRedirect('/')

wibo/templates/contacts/detail.html
{% extends "contacts/index.html" %}

{% block head_title %}{{ contact.first_name}} {{contact.last_name}}{% endblock head_title %}

{% block body %}
{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
<h3>[{{contact.id}}] {{ contact.first_name }} {{ contact.last_name }}</h3>
<h4>{{contact.department}}, {{ contact.company }}</h4>
<a class="btn" href="{% url contacts.views.edit_contact contact.id %}">Edit</a><br />
<div class="row">
<div class="span4">
    <a href="mailto:{{ contact.email }}">{{contact.email}}</a><br \>
    <b>Price Level:</b> {{contact.default_price_level}}<br \>
    {% if contact.student_id %}
    <b>Student ID:</b> {{contact.student_id}}<br \>
    {% endif %}
    {% for phone in contact.telephone_set.all %}
    <b>Phone #:</b> {{ phone.phone_number }} ({{ phone.phone_type }})<br \>
    {% endfor %}
</div>
<div class="span4">
{% if contact.address_set.count > 0 %}
    {% if contact.address_set.count == 1 %}
    <h4>Address</h4>
    {% else %}
    <h4>Addresses</h4>
    {% endif %}
    <ul class="unstyled">
        {% for address in contact.address_set.all %}
        <li><address>{{ address.street_address}}<br />
        {{address.city}}, {{address.state}} {{address.postal_code}}</address></li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
<div class="span4">
    <h4>Notes:</h4>
    <p>{{contact.notes}}</p>
    <b>Return on Investment:</b> {{contact.roi}}
</div>
</div>
<h4>Open Orders</h4>
<div class="row">
    {% for job in opened_list %}
    <div class="span4">{% include "cards/job_card.html" with c=job %}</div>
    {% endfor %}
</div>{# row #}
<h4>Closed Orders</h4>
<div class="row">
    {% for job in completed_list %}
    <div class="span4">{% include "cards/job_card.html" with c=job %}</div>
    {% endfor %}
</div>{# row #}
{% endblock body %}

wibo/templates/contacts/form.html
{% extends 'contacts/detail.html' %}
{% load bootstrap_tags %}

{% block head_title %}New Contact{% endblock head_title %}

{% block body %}

<form action="" method="post">{% csrf_token %}
    <div class="row">
    <div class="span4">
        {{ form|as_bootstrap }}
    </div>
    <div class="span4">
        <h4>Instructions</h4>
        <p>Create new clients or edit current ones with this form. You'll need to make a new contact for each company/organiztion a client is ordering for.</p>
        <h5>Clemson Employees</h5>
        <p>If the client is ordering for their department, list "Clemson University" as the company with the official department name for "Department or major." Please include an office phone number and office address. For consistancy, you can lookup this information at <a href="https://phonebook.app.clemson.edu">phonebook.app.clemson.edu</a>. </p>
        <p>If the client is making a person order, add a new contact and list "Personal" as the company.</p>
        <h5>Clemson Students</h5>
        <p>List "Clemson University" as the company with "Student (major)" for the Department. We need XID numbers for billing, so try and get one if you can.</p>
        <p>If a student is placing an order for a student organization or for a another group on campus, create a new contact with "Clemson University" as the company with the organization or group as the Department.</p>
        <h5>Everyone Else</h5>
        <p>Fill out as much information as you can. Phone numbers are particularly helpful when we have a problem producing a piece and need to get in touch with our client quickly.</p>
    </div>
    </div>

    {% include "formset_table.html" with formset=telephone_formset  %}
    {% include "formset_table.html" with formset=address_formset  %}
    <div class="form-actions">
        <input class="btn btn-primary" type="submit" value="Save" />
        <input class="btn" type="button" value="Cancel" onClick="history.go(-1);return true;" />    
    </div>
</form>

{% endblock body %}

wibo/templates/contacts/index.html
{% extends "site_base.html" %}
{% load bootstrap_tags %}

{% block head_title %}Contacts{% endblock head_title %}


{% block body %}
<h2>Contacts</h2>
<a class="btn" href="{% url contacts.views.new_contact %}">Add New +</a>
{% if contact_list %}
<table class="table table-striped table-condensed table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Department</th>
            <th>Company</th>
            <th>Telephone</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        {% for contact in contact_list %}
        <tr>
            <td><a href={% url contacts.views.detail contact.id %}>{{ contact.id }}</a></td>
            <td><a href={% url contacts.views.detail contact.id %}>{{ contact.last_name }}</a></td>
            <td><a href={% url contacts.views.detail contact.id %}>{{ contact.first_name }}</a></td>
            <td><a href={% url contacts.views.detail contact.id %}>{{ contact.department }}</a></td>
            <td><a href={% url contacts.views.detail contact.id %}>{{ contact.company }}</a></td>
            <td><a href={% url contacts.views.detail contact.id %}>{{ contact.telephone_set.all|first }}</a></td>
            <td><a href="mailto:{{contact.email}}">{{ contact.email }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
{% else %}
    <p>No context (no contacts available).</p>
    {% endif %}
{% endblock body %}

wibo/templates/contacts/new.html
{% extends "contacts/index.html" %}

{% block title %}{{block.super}} | Add New{% endblock title %}

{% block content %}
<h3>Add New Contact</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <fieldset>
        <legend>Name:</legend>
        <label for="id_first_name" class="required">First name:</label>
        <input name="first_name" maxlength="30" type="text" id="id_first_name" />
        <label for="id_last_name" class="required">Last name:</label>
        <input name="last_name" maxlength="30" type="text" id="id_last_name" />
    </fieldset>
    <fieldset>
        <legend>Details:</legend>
        <label for="id_company" class="required">Company or department:</label>
        <input name="compnay" maxlength="255" type="text" id="id_company" />
        <label for="id_email" class="required">Email:</label>
        <input name="email" maxlength="254" type="text" id="id_email" />
        <label for="id_default_price_level" class="required">Price level:</label>
        <select name="default_price_level" id="id_default_price_level">
            <option value selected="selected">- - - - - - - - </option>
            <option value="INT">internal</option>
            <option value="EXT">external</option>
        </select>
        <label for="id_student_id">Student id:</label>
        <input name="student_id" maxlength="10" type="text" id="id_student_id" />
        <p>Leave blank if not a student</p>
    </fieldset>
    <fieldset>
        <legend>Contact Information:</legend>
        <label for="id_telephone_set-0-phone_number">Phone number:</label>
        <input name="telephone_set-0-phone_number" maxlength="24" type="text" id="id_telephone_set-0-phone_number" />
        <fieldset name="address_set-0">
            <legend>Address</legend>
            <label for="id_address_set-0-street_address">Street address:</label>
            <input name="address_set-0-street_address" maxlength="255" type="text" id="id_address_set-0-street_address"  /><br />
            <label for="id_address_set-0-city">City:</label>
            <input name="address_set-0-city" maxlength="20" type="text" id="id_address_set-0-city" />
            <label for="id_address_set-0-state">State:</label>
            <input name="address_set-0-state" maxlength="20" type="text" id="id_address_set-0-state" />
            <label for="id_address_set-0-postal_code">Postal code:</label>
            <input name="address_set-0-postal_code" maxlength="20" type="text" id="id_address_set-0-postal_code" />
        </fieldset>
        <input type="submit" value="Save" />
    </fieldset>
{% endblock content %}